/c1/mppi_lockstep_host:
  ros__parameters:
    controller_frequency: 100.0
    controller_name: MPPI
    controller_plugin: nav2_mppi_controller::MPPIController
    independent_safety_veto: true
    safety_veto_horizon_s: 1.0
    MPPI:
      time_steps: 100
      model_dt: 0.01
      batch_size: 2000
      iteration_count: 1
      temperature: 0.3
      gamma: 0.015
      vx_max: 1.0
      vx_min: 0.0
      vy_max: 0.0
      wz_max: 0.9143085878302811
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.4
      prune_distance: 1.5
      transform_tolerance: 0.1
      max_robot_pose_search_dist: 2.0
      motion_model: Ackermann
      visualize: false
      regenerate_noises: false
      retry_attempt_limit: 1
      AckermannConstraints:
        min_turning_r: 1.0937226373133722
      critics:
        - ConstraintCritic
        - CostCritic
        - GoalCritic
        - GoalAngleCritic
        - PathAlignCritic
        - PathFollowCritic
        - PathAngleCritic
        - PreferForwardCritic
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        collision_cost: 1000000.0
        consider_footprint: true
        near_goal_distance: 1.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
